spring.datasource.url=jdbc:mysql://localhost:3306/db_barber
spring.datasource.username=barber
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.flyway.url=jdbc:mysql://localhost:3306/db_barber
spring.flyway.user=barber
spring.flyway.password=123456789
spring.flyway.database-type=mysql
spring.flyway.logging.level=debug